"""create_alarms_table

Revision ID: 6714d1376983
Revises: bb8825d9e75f
Create Date: 2022-07-09 09:06:46.407444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6714d1376983'
down_revision = 'bb8825d9e75f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('meridiem', sa.String(length=10), nullable=False),
    sa.Column('sound', sa.String(length=255), nullable=True),
    sa.Column('repeat', sa.String(length=255), nullable=True),
    sa.Column('snooze', sa.Boolean(), nullable=True),
    sa.Column('alarmlist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alarmlist_id'], ['alarmlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alarms')
    # ### end Alembic commands ###
