"""recreate_migrations

Revision ID: f0199e41cba5
Revises:
Create Date: 2022-07-16 11:33:19.408470

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = 'f0199e41cba5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")

    op.create_table('alarmlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('toggle', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE alarmlists SET SCHEMA {SCHEMA};")

    op.create_table('alarms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.String(length=10), nullable=False),
    sa.Column('meridiem', sa.String(length=10), nullable=False),
    sa.Column('sound', sa.String(length=255), nullable=True),
    sa.Column('repeat', sa.String(length=255), nullable=True),
    sa.Column('snooze', sa.Boolean(), nullable=True),
    sa.Column('toggle', sa.Boolean(), nullable=True),
    sa.Column('alarmlist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alarmlist_id'], ['alarmlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE alarms SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alarms')
    op.drop_table('alarmlists')
    op.drop_table('users')
    # ### end Alembic commands ###
